artifact_location: /Users/francoramirez/Documents/Universidad/practica/proyecto_hh/mlflow/0
creation_time: 1765678058430
experiment_id: '0'
last_update_time: 1765678058430
lifecycle_stage: active
name: Default
